version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
  producer:
    build:
      context: .
      dockerfile: Producer/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - 8084:8084
    links:
      - rabbitmq
  consumer:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - producer
    ports:
      - 8085:8085
    links:
      - rabbitmq